### ISSUE TITLE
Some question about your code about the paper [2]

### ISSUE THREAD

**Issue by TFLQW** [mginesi/dmp_vol_obst#1]
Recently i have run the package, But in the one_obstacle and two_obstacle.py , i try to change the obstacle poition and your proposed method is ok, but the paper[2] method didn't make any changes. Is it the imperfection of the paper[2] or the  your programming problem on the paper[2].
Thank your contribution.

**Comment by mginesi** [comment]
Hi, thank you for your interest.
How did you modify the obstacle for paper [2] in the test script?
I just played around with one_obstacle.py and noticed this behavior. However, even if the trajectory seems not to change, they are a bit different (you can also track the forcing term to see that the perturbations are actually different).
Moreover, I tested the script one_obstacle.py using 100 points instead of 50 for the method presented in [2] and by changing the position of the obstacle, the difference in trajectories is visible.

Moreover, this new test proves how hard is to model an obstacle using only point obstacles.

![100_p_new_pos](https://user-images.githubusercontent.com/30355881/55225581-3cd59f80-5213-11e9-8609-78972bdf5ae1.png)
![100_p_orig_pos](https://user-images.githubusercontent.com/30355881/55225582-3d6e3600-5213-11e9-84a2-28b2e370667d.png)

**Comment by TFLQW** [comment]
> 
> 
> Hi, thank you for your interest.
> How did you modify the obstacle for paper [2] in the test script?
> I just played around with one_obstacle.py and noticed this behavior. However, even if the trajectory seems not to change, they are a bit different (you can also track the forcing term to see that the perturbations are actually different).
> Moreover, I tested the script one_obstacle.py using 100 points instead of 50 for the method presented in [2] and by changing the position of the obstacle, the difference in trajectories is visible.
> 
> Moreover, this new test proves how hard is to model an obstacle using only point obstacles.
> 
> ![100_p_new_pos](https://user-images.githubusercontent.com/30355881/55225581-3cd59f80-5213-11e9-8609-78972bdf5ae1.png)
> ![100_p_orig_pos](https://user-images.githubusercontent.com/30355881/55225582-3d6e3600-5213-11e9-84a2-28b2e370667d.png)

Thanks for your answer, i think i have found the essential issues of this behaviors, i tried to modulate the parameters of gamma, which represents the sensitivity to the obstacles, when i changed it to 1000,  the computing time has increased, for decreasing the time, i changed it to 200~500, i can achieve the obastacle avoidance.

**Comment by mginesi** [comment]
Good, I close the issue! Thanks again for your interest
